image:
  repository: serviceone1.azurecr.io/glpi
  tag: latest
  pullPolicy: IfNotPresent

mariadb:
  image: mariadb
  tag: 11.0
  rootPassword: changeme-root
  user: glpiuser
  userPassword: changeme-user
  database: glpidb

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  size: 5Gi
  storageClass: default
