image:
  repository: serviceone1.azurecr.io/glpi
  tag: latest
  pullPolicy: IfNotPresent

mariadb:
  image: mariadb
  tag: 11.0
  rootPassword: pass
  user: glpiuser
  userPassword: pass
  database: glpidb

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  size: 5Gi
  storageClass: default
