image:
  repository: glpi/glpi
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: 
 - name: acr-secret

mariadb:
  image: mariadb
  tag: 11.0.3
  rootPassword: pass
  user: glpiuser
  userPassword: pass
  database: glpidb

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  size: 5Gi
  storageClass: glpi-retain
  reclaimPolicy: Retain
  
ingress:
  enabled: true
  className: traefik
  host: glpi.naveenkumarsakthivel.online   # replace with your domain
  tls:
    enabled: true
    secretName: glpi-tls
    clusterIssuer: letsencrypt-prod
