apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glpi-ingress
  namespace: glpi
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - naveenkumarsakthivel.online   # replace with your domain
      secretName: glpi-tls
  rules:
    - host: naveenkumarsakthivel.online 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glpi-service
                port:
                  number: 80
